# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cidr < Formula
  desc "CLI to perform various actions on CIDR ranges"
  homepage "https://github.com/bschaatsbergen/cidr"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bschaatsbergen/cidr/releases/download/v1.0.2/cidr_1.0.2_darwin_amd64.tar.gz"
      sha256 "d662dfc6a62cf1ad315a72c9de5777275482ab0050cba94f4bcf81c0e15965f5"

      def install
        bin.install "cidr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bschaatsbergen/cidr/releases/download/v1.0.2/cidr_1.0.2_darwin_arm64.tar.gz"
      sha256 "b6135c3ee4014f10ca1374af0f87ab3c6ce7cfd98919b6bb562360e0f8e2f1af"

      def install
        bin.install "cidr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bschaatsbergen/cidr/releases/download/v1.0.2/cidr_1.0.2_linux_arm64.tar.gz"
      sha256 "0537c094ccde24cc0791d561a46192fdf0dbb5421069be41b1dd6a75641ca654"

      def install
        bin.install "cidr"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bschaatsbergen/cidr/releases/download/v1.0.2/cidr_1.0.2_linux_amd64.tar.gz"
      sha256 "4ff412b7d7fe7b43bcb7b3809080ba139f20208fd0ef7d5f60d851b578a04afa"

      def install
        bin.install "cidr"
      end
    end
  end

  test do
    system "#{bin}/cidr -v"
  end
end
